# Packet type/class/command constants

# BLEAPI_PTYPE
UNKNOWN = 0
CMD = 1
RSP = 2
EVT = 3

# BLEAPI_PCLASS
SYSTEM = 1
MEASURE = 2
DIAG = 3

# BLEAPI_PCMD_SYSTEM
SYSTEM_READ_SYSINFO = 0x01
SYSTEM_READ_BATTERY = 0x02

# BLEAPT_PEVT_SYSTEM
SYSTEM_BATTERY_STATUS = 0x01
SYSTEM_ERROR = 0x02
SYSTEM_CONN_READY = 0x03
IMU_UPDATE = 0x04

# BLEAPI_PCMD_MEASURE
MEASURE_WRITE_CAL = 0x01
MEASURE_READ_CAL = 0x02
MEASURE_CONFIG_CAL = 0x03
MEASURE_BEGIN_CAL = 0x04
MEASURE_CONFIG_SESS = 0x06
MEASURE_BEGIN_SESS = 0x07
MEASURE_END_SESS = 0x0A

# BLEAPI_PEVT_MEASURE
MEASURE_COMPLETE_CAL = 0x01

# BLEAPI_PCMD_DIAG
DIAG_READ_IMU = 0x01

# BLEAPI_PEVT_DIAG
DIAG_MEASURE_COMPLETE = 0x01


# Name maps for commands/response and event codes

CMD_NAME_MAP = {
    SYSTEM: {
        SYSTEM_READ_SYSINFO: "SYSTEM_READ_SYSINFO",
        SYSTEM_READ_BATTERY: "SYSTEM_READ_BATTERY",
    },
    MEASURE: {
        MEASURE_WRITE_CAL: "MEASURE_WRITE_CAL",
        MEASURE_READ_CAL: "MEASURE_READ_CAL",
        MEASURE_CONFIG_CAL: "MEASURE_CONFIG_CAL",
        MEASURE_BEGIN_CAL: "MEASURE_BEGIN_CAL",
        MEASURE_CONFIG_SESS: "MEASURE_CONFIG_SESS",
        MEASURE_BEGIN_SESS: "MEASURE_BEGIN_SESS",
        MEASURE_END_SESS: "MEASURE_END_SESS",
    },
    DIAG: {
        DIAG_READ_IMU: "DIAG_READ_IMU",
    }
}

EVT_NAME_MAP = {
    SYSTEM: {
        SYSTEM_BATTERY_STATUS: "SYSTEM_BATTERY_STATUS",
        SYSTEM_ERROR: "SYSTEM_ERROR",
        SYSTEM_CONN_READY: "SYSTEM_CONN_READY",
        IMU_UPDATE: "IMU_UPDATE",
    },
    MEASURE: {
        MEASURE_COMPLETE_CAL: "MEASURE_COMPLETE_CAL",
    },
    DIAG: {
        DIAG_MEASURE_COMPLETE: "DIAG_MEASURE_COMPLETE",
    }
}


# Pod/emitter property constants

# pod_id_t
POD1 = 1
POD2 = 2

# PODDetectorIDTypeDef
DX = 0
D0 = 1
D1 = 2

# ActivePathFlagTypeDef
INACTIVE = 0
ACTIVE = 1

# PODEmitterLocationIDTypeDef
NO_EMITTER = 0
F1 = 1
R1 = 2
S0 = 3
S1 = 4

# EmitterWavelengthTypeDef
L740 = 0
L850 = 1


# Constants defining headset hardware properties

NUM_MEASUREMENTS_PER_POD = 8
NUM_PATHS_PER_POD = 12
NUM_PODS = 2

NUM_MEASUREMENTS = NUM_MEASUREMENTS_PER_POD * NUM_PODS
NUM_PATHS = NUM_PATHS_PER_POD * NUM_PODS
BLEAPI_NUM_PATHS_IN_SYSTEM = NUM_PATHS


# Packet version constants

MEASUREMENT_PACKET_V1 = 0x0001
MEASUREMENT_PACKET_V2 = 0x0002
MEASUREMENT_PACKET_V3 = 0x0003
MEASUREMENT_PACKET_V7 = 0x000A


# Preambles for headset packets

HEADER_PREAMBLE = 0xF0CA
HEADER_PREAMBLE_BYTES = HEADER_PREAMBLE.to_bytes(2, 'little')

DATA_PREAMBLE = 0xF0CAF0CA
DATA_PREAMBLE_BYTES = DATA_PREAMBLE.to_bytes(4, 'little')


# Packet result codes

RESULT_SUCCESS = 0x0001
RESULT_NOT_IMPLEMENTED = 0x0002
RESULT_UNKNOWN_COMMAND = 0x0003
RESULT_INCOMPLETE_COMMAND = 0x0004
RESULT_CMD_FAILED = 0x1001
RESULT_CMD_PARAMETER_OUT_OF_RANGE = 0x1002
RESULT_CMD_FAILED_CALIBRATION_ACTIVE = 0x2001
RESULT_CMD_FAILED_SESSION_ACTIVE = 0x2002
RESULT_CMD_FAILED_SESSION_NOT_ACTIVE = 0x2003
RESULT_CMD_FAILED_NO_CAL_DATA = 0x2004
RESULT_CMD_FAILED_OPS_BUSY = 0x2005


# Bluetooth UART UUIDs for identifying/connecting to headset

UART_SERVICE_UUID = "6e400001-b5a3-f393-e0a9-e50e24dcca9e"
UART_RX_CHARACTERISTIC_UUID = "6e400002-b5a3-f393-e0a9-e50e24dcca9e"
UART_TX_CHARACTERISTIC_UUID = "6e400003-b5a3-f393-e0a9-e50e24dcca9e"

UART_SERVICE_UUID_V3 = "cd0ee03a-b724-4365-9a6e-3e2ee64b4a43"
UART_RX_CHARACTERISTIC_UUID_V3 = "cd0e0002-b724-4365-9a6e-3e2ee64b4a43"
UART_TX_CHARACTERISTIC_UUID_V3 = "cd0e0003-b724-4365-9a6e-3e2ee64b4a43"

UART_UUIDS = {
    UART_SERVICE_UUID: {
        'service': UART_SERVICE_UUID,
        'rx': UART_RX_CHARACTERISTIC_UUID,
        'tx': UART_TX_CHARACTERISTIC_UUID,
    },
    UART_SERVICE_UUID_V3: {
        'service': UART_SERVICE_UUID_V3,
        'rx': UART_RX_CHARACTERISTIC_UUID_V3,
        'tx': UART_TX_CHARACTERISTIC_UUID_V3,
    }
}
